### ISSUE TITLE
Ergkeeper domain doesn't exist anymore

### ISSUE THREAD

**Issue by polydroid** [nugget/ergkeeper#7]
I was trying use Ergkeeper.com to upload my concept2 log into runkeeper.com and found the domain is not working.

**Comment by nugget** [comment]
Can you clarify what you mean by "not working?"  Site is up and I show user activity and successful uploads as recently as this afternoon.

**Comment by polydroid** [comment]
It was my browser issue. I will remove my comment/issue. 
sorry for the trouble

**Comment by nugget** [comment]
No worries, at all.  Let me know if you have any problems.
