### ISSUE TITLE
Ergkeeper keep saying my Runkeeper access revoked

### ISSUE THREAD

**Issue by polydroid** [nugget/ergkeeper#8]
Hello again, David! 
Even though I have logged into RunKeeper account and given access to Ergkeeper app, it is keep saying RunKeeper has revoked my access when trying to signing in through it. Followed by this, I deleted the ergkeeper app from RunKeeper few times and given access access, and result is the same. 

Any ideas or suggestion or have you seen this before? 

Thanks again, 

Sateesh

**Comment by nugget** [comment]
Very odd, I see your user registration on my end and it looks normal and has a runkeeper oauth token.   I'll see if I can reproduce.  I'm a bit distracted by the holidays but I should have time to look soon.

**Comment by polydroid** [comment]
No problem.  Take your time and let me know if you have any questions. 

Thanks

**Comment by nugget** [comment]
I am able to reproduce your problem but from this end everything looks normal.  I just removed your user record entirely from this side and perhaps if you re-link or re-login it will fix the glitch.  Maybe my end isn't properly revising the oauth token or somehow that managed to get desynched from the runkeeper side.

We'll get this working!  Sorry for the problems.

**Comment by polydroid** [comment]
perfect! it worked now! 
Thank you very much!!

**Comment by nugget** [comment]
Yay!
